---
title: "ENV 790.30 - Time Series Analysis for Energy Data | Spring 2023"
subtitle: "Assignment 1 - Due date 01/24/23"
author: "Maggie O'Shea"
output: pdf_document
geometry: margin=2.54cm
---

## Directions

Before making any edits to this file, please rename it such that it includes your first and last name (e.g., "LuanaLima_TSA_A01_Sp23.Rmd")

Once you have this renamed file open in RStudio, the first thing you will do is replace "Student Name" on line 3 with your name. 
Then you will start working through the assignment by  **creating code and output** that answer each question. Be sure to use this assignment document. Your report should contain the answer to each question and any plots/tables you obtained (when applicable).

When you have completed the assignment, **Knit** the text and code into a single PDF file.  Submit this pdf using Sakai. 

## Questions

Q1. What are your previous experiences with time series analysis, R, and Git? 

> Answer: My only exposure to Time Series analysis is the module within the Environmental Data Analytics course. Thus, I have a preliminary understanding of basic Time Seris but do not have a complex or nuanced understanding of the analysis at all. As for R, I have taken many classes that require that I use R and for my summer internship and Masters Thesis I am using R to conduct my analysis, create my visualizations, and possibly write the report as well. Finally, I am fairly comfortable in Git - I used it in EDA, as well as geospatial data analytics, and, finally, through my work this summer, used Git to work collaboratively on a data science project. 


Q2. (Only if you choose to use git) Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and **that you have updated your course README file as instructed on the recorded video "Getting started with Git and Github".** 

> Answer: https://github.com/maggieoshea/TimeSeriesAnalysis_Sp23


Q3. For this part we just want to see the path to your R project. No need to do anything. The output will be automatically generated once you knit you file. 

> Answer: This is my working directory:

```{r}
getwd()
````


